# Adjust sources
RTL = ./alu.sv \
      ./control_unit.sv \
      ./decode_unit.sv \
      ./pc.sv \
      ./reg_file.sv \
      ./riscv_core.sv \
      ./fpga_top.sv
TOP = fpga_top

# Include base Makefile
include ../../../makefile.include
